name: Unit test
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test GetIPv4Subnet module
        shell: pwsh
        run: |
          Invoke-Pester -Passthru
